app:
  name: demo
  host: 127.0.0.1
  port: 1910
  debug: True
  secret_path: '/home/sergey-msu/Work/startup/polaris/_secret/keys.yml'
  template_dir: views
  static_dir: static
classifier:
  host: 127.0.0.1
  port: 1909
  endpoint: classify
